//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uzPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractValue
    {
        public int id { get; set; }
        public int ContractID { get; set; }
        public string Kod { get; set; }
        public string Name { get; set; }
        public string CostOne { get; set; }
        public string Count { get; set; }
        public string CostAll { get; set; }
        public string Sale { get; set; }
        public string Total { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
