//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uzPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractValues = new HashSet<ContractValue>();
        }
    
        public int id { get; set; }
        public string NumContract { get; set; }
        public string NumAct { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public string Pasport { get; set; }
        public string Reg { get; set; }
        public string Tel { get; set; }
        public int ProtocolID { get; set; }
    
        public virtual Protocol Protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractValue> ContractValues { get; set; }
    }
}
